### PR TITLE
Getenv wrapper to return a default value if an environment variable isn't there

### PR DESCRIPTION
**Pull request by lvillani**
I'm a bit unsure whether to call this function `Getenv` or `GetenvDefault` or something else.

### CODE REVIEW

**Comment by ungerik** [comment]
There are some other very short functions in this package, but I am not sure if a single if statement needs encapsulation.

**Comment by lvillani** [comment]
We use something like this in top-level vars or package `init()` functions, like:

```.go
var (

)
```

**Comment by ungerik** [comment]
OK, this makes sense. But I would name it GetenvDefault.

**Comment by lvillani** [comment]
Renamed to `GetenvDefault`

**Pull request merged**
